/** Public key that verifies the releases' signature. Generated by `bun run keys` in update-server. */
export const UPDATE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA9rTdo7vk6cZdTqsQmB7AysmwCTRdwx8kbw29Zhsy6qA=
-----END PUBLIC KEY-----
`;
