import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { ServerPaths } from "../shared/ServerPaths";

function publicKeyModule(publicKeyPem: string): string {
  return `/** Public key that verifies the releases' signature. Generated by \`bun run keys\` in update-server. */
export const UPDATE_PUBLIC_KEY = \`${publicKeyPem}\`;
`;
}

export const KeyPair = {
  /** Creates the keys: the private one stays in `keys/` (outside git) and the public one is written into the app code. */
  generate(force: boolean) {
    if (fs.existsSync(ServerPaths.privateKeyFile) && !force) {
      throw new Error(
        "Já existe uma chave privada. Gerar outra invalida os apps já instalados; use --force se for isso mesmo.",
      );
    }

    const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519", {
      publicKeyEncoding: { type: "spki", format: "pem" },
      privateKeyEncoding: { type: "pkcs8", format: "pem" },
    });

    fs.mkdirSync(path.dirname(ServerPaths.privateKeyFile), { recursive: true });
    fs.writeFileSync(ServerPaths.privateKeyFile, privateKey, { mode: 0o600 });
    fs.writeFileSync(ServerPaths.appPublicKeyFile, publicKeyModule(publicKey));
  },

  loadPrivate(): string {
    if (!fs.existsSync(ServerPaths.privateKeyFile)) {
      throw new Error("Chave privada não encontrada. Rode `bun run keys` primeiro.");
    }
    return fs.readFileSync(ServerPaths.privateKeyFile, "utf8");
  },

  /** Avoids publishing a release that the apps could not validate. */
  assertMatchesApp() {
    const derivedPublicKey = crypto
      .createPublicKey(KeyPair.loadPrivate())
      .export({ type: "spki", format: "pem" })
      .toString();

    const appModule = fs.readFileSync(ServerPaths.appPublicKeyFile, "utf8");
    if (!appModule.includes(derivedPublicKey)) {
      throw new Error(
        "A chave pública embutida no app não corresponde à chave privada. Rode `bun run keys --force`.",
      );
    }
  },
};
