/**
 * Central icon map: names from the "app" set (used as `app~name`
 * in the <AppIcon/> component) → Material Icons icons.
 * Replaces the use of lucide-react in the React project.
 */
export const APP_ICONS = {
  search: "search",
  mic: "mic",
  close: "close",
  check: "check",
  x: "close",
  chevronDown: "expand_more",
  chevronUp: "expand_less",
  chevronLeft: "chevron_left",
  chevronRight: "chevron_right",
  arrowUp: "arrow_upward",
  arrowDown: "arrow_downward",
  plus: "add",
  minus: "remove",
  trash: "delete",
  edit: "edit",
  music: "music_note",
  fileText: "description",
  book: "menu_book",
  bookOpen: "local_library",
  calendar: "calendar_month",
  calendarPlus: "event",
  settings: "settings",
  monitor: "monitor",
  sun: "light_mode",
  moon: "dark_mode",
  sparkles: "auto_awesome",
  palette: "palette",
  image: "image",
  images: "photo_library",
  gradient: "gradient",
  type: "text_fields",
  textDecrease: "text_decrease",
  textIncrease: "text_increase",
  alignTop: "vertical_align_top",
  alignCenter: "vertical_align_center",
  alignBottom: "vertical_align_bottom",
  textAlignLeft: "format_align_left",
  textAlignCenter: "format_align_center",
  textAlignRight: "format_align_right",
  textAlignJustify: "format_align_justify",
  bold: "format_bold",
  italic: "format_italic",
  uppercase: "title",
  fade: "fade_in",
  moveUp: "vertical_align_bottom",
  flame: "local_fire_department",
  play: "play_arrow",
  upload: "upload",
  refresh: "refresh",
  maximize: "check_box_outline_blank",
  minimize: "remove",
  restore: "filter_none",
  grip: "drag_indicator",
  layoutList: "format_list_bulleted",
  listChecks: "checklist",
  alertTriangle: "warning",
  info: "info",
  bookmark: "bookmark",
  timer: "timer",
} as const;

export type AppIconName = keyof typeof APP_ICONS;
